### ISSUE TITLE
Transition to object based inputs approach

### ISSUE THREAD

**Issue by amarcozzi** [silvxlabs/quicfire-tools#14]
# TODO:
  - [x] gridlist
  - [x] rasterorigin.txt
  - [x] QU_buldings.inp
  - [x] QU_fileoptions.inp
  - [x] QU_simparams.inp
  - [x] QUIC_fire.inp
  - [x] QFire_Advanced_User_Inputs.inp
  - [x] #28
  - [x] #30
  - [x] #46
  - [x] #44
  - [x] #38
  - [x] #40
  - [x] #41
  - [x] #31
  - [x] #48

# For future:
  -  QU_landuse.inp
  -  ~~ignite.dat~~
  -  wind shifts
  - multiple wind profiles

**Comment by amarcozzi** [comment]
Nice work @ntutland !
